### ISSUE TITLE
[BUG] Prefix/Suffix not working for multi 6.101.1

### ISSUE THREAD

**Issue by xandout** [elasticsearch-dump/elasticsearch-dump#974]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 6.101.1
- Elasticsearch version:: 8.3.2
- Node.js version *(note that nodejs v10+ is required for this tool)*: 14? Built in to docker image
- Full command you are having issue with (with inputs and outputs)
- A data-set you can share publicly which reproduces the problem

**Describe the bug**
I am using multielasticdump to recover ES indices, the dumps were created by multielasticdump as well.  To run validations, I am trying to use `--prefix` or `--suffix`, however those args are not passed to the forks 

```
Wed, 31 May 2023 13:01:50 GMT | We are performing : load
Wed, 31 May 2023 13:01:50 GMT | options: 
{"debug":true,
"parallel":8,
"match":"^.*$",
"order":"asc",
"input":"/data/es_backup",
"output":"http://mloop-elasticsearch-es-http:9200",
"scrollId":null,
"scrollTime":"10m",
"scroll-with-post":false,
"timeout":null,
"limit":100,
"offset":0,
"size":-1,
"direction":"load",
"support-big-int":false,
"big-int-fields":"",
"ignoreAnalyzer":true,
"ignoreChildError":false,
"ignoreData":false,
"ignoreMapping":false,
"ignoreSettings":false,
"ignoreTemplate":false,
"ignoreAlias":true,
"ignoreIndex":true,
"ignoreType":[],
"includeType":null,
"interval":1000,
"delete":false,
"prefix":"mdt",
"suffix":"mdt",
"transform":null,
"headers":null,
"searchBody":null,
"searchWithTemplate":null,
"cert":null,
"key":null,
"pass":null,
"ca":null,
"tlsAuth":false,
"input-cert":null,
"input-key":null,
"input-pass":null,
"input-ca":null,
"output-cert":null,
"output-key":null,
"output-pass":null,
"output-ca":null,
"httpAuthFile":null,
"concurrency":1,
"carryoverConcurrencyCount":true,
"intervalCap":5,
"concurrencyInterval":5000,
"overwrite":true,
"fsCompress":false,
"awsChain":false,
"awsAccessKeyId":null,
"awsSecretAccessKey":null,
"awsIniFileProfile":null,
"awsService":null,
"awsRegion":null,
"awsUrlRegex":null,
"s3AccessKeyId":null,
"s3SecretAccessKey":null,
"s3Region":null,
"s3Endpoint":null,
"s3SSLEnabled":true,
"s3ForcePathStyle":false,
"s3Compress":false,
"s3ServerSideEncryption":null,
"s3SSEKMSKeyId":null,
"s3ACL":null,
"quiet":false

}

....

Wed, 31 May 2023 13:01:50 GMT [debug] | fork: 
/usr/local/lib/node_modules/elasticdump/bin/elasticdump --type=template
--input=/data/es_backup/application-001.template.json
--output=http://mloop-elasticsearch-es-http:9200/application-001
--headers=null
--cert=null
--key=null
--pass=null
--ca=null
--tlsAuth=false
--input-cert=null
--input-key=null
--input-pass=null
--input-ca=null
--output-cert=null
--output-key=null
--output-pass=null
--output-ca=null
--httpAuthFile=null
--concurrency=1
--carryoverConcurrencyCount=true
--intervalCap=5
--concurrencyInterval=5000
--overwrite=true
--fsCompress=false
--awsChain=false
--awsAccessKeyId=null
--awsSecretAccessKey=null
--awsIniFileProfile=null
--awsService=null
--awsRegion=null
--awsUrlRegex=null
--s3AccessKeyId=null
--s3SecretAccessKey=null
--s3Region=null
--s3Endpoint=null
--s3SSLEnabled=true
--s3ForcePathStyle=false
--s3Compress=false
--s3ServerSideEncryption=null
--s3SSEKMSKeyId=null
--s3ACL=null
--quiet=false
--scroll-with-post=false
```

**To Reproduce**

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: elasticsearch-restore
spec:
  suspend: true
  schedule: "30 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ${service_account_name}
          containers:
          - name: elasticsearch-restore
            image: elasticdump/elasticsearch-dump:v6.101.1
            imagePullPolicy: IfNotPresent
            env:
            - name: ES_URI
              value: ${elasticsearch_uri_schema}://${elasticsearch_username}:${elasticsearch_password}@${elasticsearch_hostname}:${elasticsearch_port}
            - name: BUCKET_NAME
              value: ${bucket_name}
            - name: ELASTICSEARCH_CLUSTER_NAME
              value: ${elasticsearch_cluster_name}
            command:
            - /bin/bash
            - -c
            - |
              apt update && apt install -y python3-pip && pip3 install awscli
              aws s3 cp "s3://$${BUCKET_NAME}/$${ELASTICSEARCH_CLUSTER_NAME}_LATEST.tar.gz" "LATEST.tar.gz"
              mkdir -p /data/es_backup
              tar -zxvf "LATEST.tar.gz" --strip-components 2 -C /data/es_backup
              export EN=$(date +$${ELASTICSEARCH_CLUSTER_NAME}-all-%m-%d-%Y-%s)
              multielasticdump \
                --direction=load \
                --prefix=mdt \
                --suffix=mdt \
                --overwrite \
                --match='^.*$' \
                --output=$${ES_URI} \
                --input=/data/es_backup
              sleep infinity
          restartPolicy: OnFailure
```

**Current behavior**
Prefix/Suffix NOT being applied to forked elasticdump command

**Expected behavior**
Prefix/Suffix being applied to forked elasticdump command
